# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#export PATH=$PATH:~/.gem/ruby/2.6.0/bin/
#export PATH=$PATH:~/.rbenv/shims
#eval "$(rbenv init -)"
#export PATH=$PATH:~/.config/composer/vendor/bin/

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
autoload -Uz promptinit
promptinit
prompt powerlevel10k
QT_IM_MODULE=fcitx

#alias
alias textemp='cp ~/Documents/latextemp.tex `pwd`/report.tex'
alias ls='exa --icons'
alias lt='exa --icons --tree -L 3'
bindkey -e

export PATH=$HOME/.local/bin:$PATH
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh

# ls after cd
chpwd(){
  if [[ $(pwd) != $HOME ]]; then;
    ls
  fi
}
# eval "$(starship init zsh)"
