#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#export PATH=$PATH:~/.gem/ruby/2.6.0/bin/
#export PATH=$PATH:~/.rbenv/shims
#eval "$(rbenv init -)"
#export PATH=$PATH:~/.config/composer/vendor/bin/

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
autoload -Uz promptinit
promptinit
prompt powerlevel10k
QT_IM_MODULE=fcitx
